kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:8.10.2-jdk21-jammy
    commands:
      - export BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - gradle test --no-daemon

  - name: publish
    image: gradle:8.10.2-jdk21-jammy
    environment:
      ARTEFACTS_USER:
        from_secret: ARTEFACTS_USER
      ARTEFACTS_PASSWORD:
        from_secret: ARTEFACTS_PASSWORD
    commands:
      - export BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - apt-get update && apt-get install -y curl
      - gradle --no-daemon --build-cache jlinkTar publish
    when:
      ref:
        - refs/heads/master
