kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:7.3.1-jdk11
    commands:
      - gradle test --no-daemon
  - name: publish
    image: gradle:7.3.1-jdk11
    environment:
      ARTEFACTS_USER:
        from_secret: ARTEFACTS_USER
      ARTEFACTS_PASSWORD:
        from_secret: ARTEFACTS_PASSWORD
    commands:
      - gradle execJar publish --no-daemon
      - "export CI_BUILD=$(gradle properties | grep 'version:' | sed 's/version: //') && \
      ./etc/publish.sh https://code.shrimpworks.za.net/artefacts/unreal-archive-submitter ./build/libs/unreal-archive-submitter ./build/libs/unreal-archive-submitter-exec.jar"
    when:
      ref:
        - refs/heads/master
