dist: xenial
language: java

jdk:
  - openjdk11

before_cache:
  - rm -f  ~/.gradle/caches/modules-2/modules-2.lock
  - rm -fr ~/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - ~/.gradle/caches/
    - ~/.gradle/wrapper/

jobs:
  include:
    - stage: test
      script: ./gradlew test
    - stage: build and publish binaries
      if: branch = master
      script:
        - ./gradlew execJar
        - ./etc/publish.sh https://code.shrimpworks.za.net/artefacts/unreal-archive-submitter ./dist/unreal-archive-submitter ./dist/unreal-archive-submitter-exec.jar
