language: java
jdk:
  - openjdk8

cache:
  directories:
    - /home/travis/.ant/

jobs:
  include:
    - stage: test
      script: ant test
    - stage: build and publish binaries
      if: branch = master
      script:
        - ant bin
        - ./resources/publish.sh https://code.shrimpworks.za.net/artefacts/unreal-archive-submitter ./dist/unreal-archive-submitter ./dist/unreal-archive-submitter-exec.jar

