on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Test
        run: ./gradlew --no-daemon test

      - name: Publish
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
          BUILD_NUMBER: ${{ gitea.run_number }}
        run: |
          ./gradlew --no-daemon --build-cache jlinkTar publish
